export const PRISMA_CLIENT = 'PRISMA_CLIENT'
export const PRISMA_CONNECTION_NAME = Symbol('PRISMA_CONNECTION_NAME')
export const PRISMA_CONNECTIONS = Symbol('PRISMA_CONNECTIONS')
export const PRISMA_MODULE_OPTIONS = Symbol('PRISMA_MODULE_OPTIONS')
